driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian
    run_list:
      - recipe[pip_elastalert_test::elasticsearch]

suites:
  - name: default
    run_list:
      - recipe[pip_elastalert]
      - recipe[pip_elastalert_test::add_rule]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
